### ISSUE TITLE
Badges

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#105]
There is a suggestion to show badges in the student profiles (Like in HackerRank / GitHub) 

- Special Project Contributions 
- Department issued certificates 

Under development: https://nuwanj.github.io/people.ce.pdn.ac.lk/badges/
[Edit] Repo Link - https://github.com/NuwanJ/people.ce.pdn.ac.lk

#### ToDo

- [x] Prepare the documentation 
- [x] Prepare the templates
- [x] Prepare content descriptions for each badge - with Dr. Damayanthi
- [x] Discuss the Casual Instructor Program - with Dr. Isuru 
- [ ] Add previous casual instructors

**Comment by NuwanJ** [comment]
this is a test

**Comment by NuwanJ** [comment]
New feature request:

Add an option to link a certificate (PDF) into the badge details
