### ISSUE TITLE
Design the student md file with YAML header

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#2]
#### TODO
- [x] Identify the parameters 
- [x] Add necessary tags 
- [x] Decide folder structure
   - [x] md file
   - [x] image 
- [x] Implement 
- [x] Create files for existing students
