### ISSUE TITLE
Design the API for people

### ISSUE THREAD

**Issue by NuwanJ** [cepdnaclk/people.ce.pdn.ac.lk#3]
#### TODO

- [ ] Identify the possible requirements 
- [ ] Write pre-processor python scripts 
- [ ] Design the APIs
- [ ] Implement
